# Generated by Django 4.0 on 2022-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('donar_id', models.IntegerField()),
                ('ngo_id', models.IntegerField()),
                ('donation_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('donation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequestModel',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('donar_id', models.IntegerField()),
                ('ngo_id', models.IntegerField()),
                ('donation_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DonorModel',
            fields=[
                ('donar_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngo_id', models.IntegerField()),
                ('donar_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NGOModel',
            fields=[
                ('ngo_id', models.AutoField(primary_key=True, serialize=False)),
                ('ngo_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('started_in', models.DateField()),
                ('documents', models.CharField(max_length=100)),
            ],
        ),
    ]
