# Generated by Django 4.0 on 2022-06-15 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='donar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donationapp.donormodel'),
        ),
    ]
