# Generated by Django 4.0 on 2022-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0002_alter_donationmodel_donar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='donar_id',
            field=models.IntegerField(),
        ),
    ]
